apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
data:
  TZ: Europe/Vilnius
  MYSQL_ROOT_PASSWORD: rootpw
  MYSQL_USER: domjudge
  MYSQL_PASSWORD: djpw
  MYSQL_DATABASE: domjudge
  MYSQL_HOST: mariadb-svc
