version: '3'
services:
  mariadb:
    image: mariadb:10.9.6
    volumes:
      - mariadb-vol:/var/lib/mysql
    environment:
      - TZ=Europe/Vilnius
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    restart: unless-stopped

  domserver:
    image: domjudge/domserver:latest
    ports:
      - 8080:80
    environment:
      - CONTAINER_TIMEZONE=Europe/Vilnius
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
      - MYSQL_HOST=mariadb
    depends_on:
      - mariadb
    restart: unless-stopped

  judgehost0:
    image: domjudge/judgehost:latest
    hostname: judgehost0
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - DAEMON_ID=0
      - CONTAINER_TIMEZONE=Europe/Vilnius
      - JUDGEDAEMON_USERNAME=judgehost
      - JUDGEDAEMON_PASSWORD=password
      - DOMSERVER_BASEURL=http://domserver/
    depends_on:
      - domserver
    restart: unless-stopped

  judgehost1:
    image: domjudge/judgehost:latest
    hostname: judgehost1
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - DAEMON_ID=1
      - CONTAINER_TIMEZONE=Europe/Vilnius
      - JUDGEDAEMON_USERNAME=judgehost
      - JUDGEDAEMON_PASSWORD=password
      - DOMSERVER_BASEURL=http://domserver/
    depends_on:
      - domserver
    restart: unless-stopped

volumes:
  mariadb-vol: